### ISSUE TITLE
Add /probe documentation on README.md and Prometheus config

### ISSUE THREAD

**Issue by matanbaruch** [shift/domain_exporter#43]
Add /probe documentation on README.md and Prometheus config

URL: `http://localhost:9203/probe?target=google.com`

Prometheus config:
```
 - job_name: 'domain-exporter'
    metrics_path: /probe
    static_configs:
      - targets:
        - google.com  # Target to probe with whois.
        - facebook.com  # Target to probe with whois.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9203  # The domain exporter's real hostname:port.
 ```
